### ISSUE TITLE
Travis build for this repo is still using Python CLI

### ISSUE THREAD

**Issue by jasonpet** [openwhisk/openwhisk-package-rss#10]
The Python CLI is being removed.  You need to update travis.yml to pass in the location to the Go CLI.  You will also need to handle security for Go CLI.  For example, -i is needed to bypass security with Go CLI.

**Comment by lzbj** [comment]
@jasonpet ,agree with you. Better let's try to to integrate with the package installation tool later.

**Comment by lzbj** [comment]
Close this one as we track the CI and test with issue #15. thanks.
