### ISSUE TITLE
Whisk object is deprecated going forward replave with NPM

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk-package-rss#13]
What the title says.

See both:
https://www.npmjs.com/package/openwhisk
https://medium.com/openwhisk/updates-to-openwhisk-node-js-actions-ed5556cd5ae9#.xtcrclic4

For how to change to the OpenWhisk NPM package and promises instead of using the whisk object.

**Comment by lzbj** [comment]
I'll try to integrate it with the latest OpenWhisk promise.

**Comment by lzbj** [comment]
close as fixed
