### ISSUE TITLE
Enable Travis and scanCode.py, and make Travis pass.

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk-package-rss#15]
It looks like there was an attempt to create the files in order to do a Travis build, but it appears it was never finished.  Manual codescan revealed several errors (which were fixed on PR #14 :

This indicated Travis was never run.

**Comment by lzbj** [comment]
I think we can do the following steps.
1. Install a local OpenWhisk on this repo.
2. Use wskdeploy or wskcli deploy the feed.
3. Use wskcli to verify the trigger could be created or deleted with the feed, RSSTests.scala perhaps needs deprecated.

**Comment by lzbj** [comment]
close as pr merged
